#HTTP Server
server: 
  port: 1111
    
#Discovery Server Acces
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /infoCatalogo
    healthCheckUrlPath: /healthCatalogo
    metadataMap:
      appOwner: israellopz
      description: aplicación ejemplo microservicios catalogo
      

#Spring configuration
spring:
  application:
    name: servicio.catalogo    

#Servidor UAA
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9999/user
 
#------------------------------------- CONEXION BASE DE DATOS ---------------------------------------------
spring.datasource:
   url: jdbc:mysql://localhost/tienda
   username: root
   password: 1i9l6p205
   driver-class-name: com.mysql.jdbc.Driver

spring.jpa:
   show-sql: true
   hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#----------------------------------------------------------------------------------------------------------------
