#HTTP Server
server: 
  port: 2222
  
#Discovery Server Acces
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /infoCesta
    healthCheckUrlPath: /healthCesta
    metadataMap:
      appOwner: israellopz
      description: aplicación ejemplo microservicios cesta   
         

#Spring configuration
spring:
  application:
    name: servicio.cesta


#Actuador Hystrix stream
#management.endpoints.web.exposure.include: hystrix.stream
      
      
#------------------------------------- CONEXION BASE DE DATOS ---------------------------------------------
spring.datasource:
   url: jdbc:mysql://localhost/tienda
   username: root
   password: 1i9l6p205
   driver-class-name: com.mysql.jdbc.Driver

spring.jpa:
   show-sql: true
   hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#----------------------------------------------------------------------------------------------------------------
